# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69476d8e926aef9a5463ebb7339b5148641f6555fa10e68549ceb5977b5f6cff9a9442c5749b8809218e76f836531004fad990a124e2eccb26fdeab83a586b26

test:
  secret_key_base: 85fba8fdf610d927b9eca7e842b3ffeb8462b3196fa8327e1aad8e17b9b2dc1240b01b74be8d6ad2c43abb381a8b9ab1cbd5cb201a7cc102162d6d1d197c4408

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
